#!/bin/bash
set -eu

# Pre-exec
if [[ -d exec.d ]]; then
    shopt -s nullglob
    for f in exec.d/*/charm-pre-install; do
    [[ -x "$f" ]] || continue
    ${SHELL} -c "$f"|| {
        ## bail out if anyone fails
        juju-log -l ERROR "$f: returned exit_status=$? "
        exit 1
    }
    done
fi


apt-add-repository -y ppa:charmsupport/ppa
apt-get update

# charmsupport for persistent storage support
apt-get install python-charmsupport

# default-jdk should be a prerequisite for jetty (Bug#1046732)
apt-get install -y solr-jetty default-jdk curl
