#!/bin/bash
pgrep jsvc 2>&1 > /dev/null
if [[ $? -eq 0 ]]; then
    juju-log "solr-jetty already started"
    exit 0
fi
/etc/init.d/jetty start
# Wait for solr-jetty to start responding
host_ip=$(unit-get private-address)
curl_rc=-1
counter=0
while [[ $curl_rc -ne 0 ]]; do
    juju-log "Waiting for solr-jetty to respond ($counter)"
    curl --max-time 5 --silent "http://${host_ip}:8080/solr/select?q=test" 2>&1 > /dev/null
    curl_rc=$?
    if [[ $counter -gt 5 ]]; then
        juju-log "solr-jetty not responding"
        exit 1
    fi
    sleep 2
    let counter++
done
